"""--------------------------------------------------------------------------------
stratifiedDataGen.py

Created: June 2026
Authors: Susan Fox, Jana Abu-Subha

stratifiedDataGen.py contains trials of a new stratified data split. This split is used in traintestsplit()
in DataGeneratorVIVIT, and was created to combat the overfitting found in previous iterations of the VIVIT model.
Variations of stratified_run_split (commented out) were generated by Gemini, and include differing approaches to
splitting runs to training and validation data: splitting based on presence of a cell only, presence and volume of a cell,
or only volume.

--------------------------------------------------------------------------------"""

import os
import numpy as np

mainPath = "/home/macalester/PycharmProjects/catkin_ws/src/match_seeker/res/"
evalPath = os.path.join(mainPath, "classifier2022Data/DATA/")
framesDataPath = os.path.join(evalPath, "FrameData/")
annotFolder = os.path.join(evalPath, "AnnotData/")

def matrix_maker():
    """
    Creates a binary matrix indicating which locations are present in each run, with a 1 at
    """
    num_locations = 271
    runs = sorted(os.listdir(annotFolder))
    num_runs = len(runs)
    run_location_matrix = np.zeros((num_runs, num_locations))

    for run_idx, run in enumerate(runs):
        file_path = os.path.join(annotFolder, run)

        with open(file_path, 'r') as f:
            cells_in_run = {line.split()[3] for line in f if line.strip()}

        for cell in cells_in_run:
            cell_id = int(cell)
            run_location_matrix[run_idx, cell_id] = 1

    return runs, run_location_matrix


def stratified_run_split(run_ids, run_matrix, train_size=0.8):
    """
    Splits whole runs into train/val while balancing the 271 location classes.
    """
    train_runs = []
    val_runs = []

    # Track how many times each location has been assigned to train vs val
    train_counts = np.zeros(run_matrix.shape[1])
    val_counts = np.zeros(run_matrix.shape[1])

    # Sort runs by rarity: runs with fewer locations or rarest locations are placed first
    run_rarity = np.sum(run_matrix, axis=1)
    sorted_run_indices = np.argsort(run_rarity)

    for idx in sorted_run_indices:
        run_id = run_ids[idx]
        run_profile = run_matrix[idx]

        # Calculate current balance score if we add to train vs val
        # We want to maintain a specific ratio (e.g., 4:1 for an 80/20 split)
        expected_ratio = train_size / (1 - train_size)

        # Check which set needs these locations more urgently
        # train_score = np.sum(run_profile * (train_counts == 0))
        # val_score = np.sum(run_profile * (val_counts == 0))
        #
        # if train_score >= val_score * expected_ratio:
        #     train_runs.append(run_id)
        #     train_counts += run_profile
        # else:
        #     val_runs.append(run_id)
        #     val_counts += run_profile


        # # alternative to checking presence, we can check abundance
        # # Calculate the total current assignment load of this run's locations
        # train_overlap = np.sum(train_counts * run_profile)
        # val_overlap = np.sum(val_counts * run_profile)
        #
        # # If training set's presence of these classes is lagging behind the target ratio,
        # # give it to training; otherwise give it to validation.
        # if train_overlap <= val_overlap * expected_ratio:
        #     train_runs.append(run_id)
        #     train_counts += run_profile
        # else:
        #     val_runs.append(run_id)
        #     val_counts += run_profile

        # TIER 1: Check if this run can rescue any completely unrepresented locations
        train_missing_contrib = np.sum(run_profile * (train_counts == 0))
        val_missing_contrib = np.sum(run_profile * (val_counts == 0))

        if train_missing_contrib != val_missing_contrib:
            # One side strictly needs this run more to uncover hidden locations
            if train_missing_contrib > val_missing_contrib:
                train_runs.append(run_id)
                train_counts += run_profile
            else:
                val_runs.append(run_id)
                val_counts += run_profile
        else:
            # TIER 2: It's a tie (or no new locations). Balance based on total volume.
            train_overlap = np.sum(train_counts * run_profile)
            val_overlap = np.sum(val_counts * run_profile)

            if train_overlap <= val_overlap * expected_ratio:
                train_runs.append(run_id)
                train_counts += run_profile
            else:
                val_runs.append(run_id)
                val_counts += run_profile

    return train_runs, val_runs


# Execute the split
runs, run_location_matrix = matrix_maker()
train_run_list, val_run_list = stratified_run_split(
    runs,
    run_location_matrix,
    train_size=0.80  # 80% train, 20% validation
)

print(f"Total Runs Assigned to Training: {len(train_run_list)}")
print(f"Total Runs Assigned to Validation: {len(val_run_list)}")

# --- 3. VERIFY THE CLASS DISTRIBUTION BALANCE ---
# Ensure your rarest locations are present in both sets
train_indices = [runs.index(r) for r in train_run_list]
val_indices = [runs.index(r) for r in val_run_list]

train_loc_distribution = np.sum(run_location_matrix[train_indices], axis=0)
val_loc_distribution = np.sum(run_location_matrix[val_indices], axis=0)

# Check for unrepresented locations in validation
missing_in_val = np.where(val_loc_distribution == 0)[0]
print(f"Number of locations completely missing from Validation: {len(missing_in_val)}")
